### ISSUE TITLE
Error include rika_gsm.cpp

### ISSUE THREAD

**Issue by Texier54** [n-serrette/esphome_rika_gsm#2]
Hi,
Thanks for the project
I try to use your custom component but i have this error :

INFO ESPHome 2024.10.3
INFO Reading configuration /config/esphome/stove.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing stove (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- noise-c @ 0.1.6
Compiling .pioenvs/stove/src/esphome/components/rika_gsm/rika_gsm.cpp.o
Compiling .pioenvs/stove/src/main.cpp.o
In file included from src/esphome/components/rika_gsm/rika_gsm.cpp:4:
src/esphome/components/rika_gsm/rika_gsm.h:68:72: error: expected template-name before '<' token
 template<typename... Ts> class RikaGsmSendCommandAction : public Action<Ts...> {
                                                                        ^
src/esphome/components/rika_gsm/rika_gsm.h:68:72: error: expected '{' before '<' token
Archiving .pioenvs/stove/lib64d/libWiFi.a
*** [.pioenvs/stove/src/esphome/components/rika_gsm/rika_gsm.cpp.o] Error 1
/config/esphome/stove.yaml: In lambda function:
/config/esphome/stove.yaml:23:14: error: could not convert 'command' from 'std::__cxx11::string' {aka 'std::__cxx11::basic_string<char>'} to 'std::vector<unsigned char>'
         - uart.write: !lambda "return command;"
              ^~~~~~~
*** [.pioenvs/stove/src/main.cpp.o] Error 1
========================= [FAILED] Took 16.98 seconds =========================

**Comment by n-serrette** [comment]
Hi,
Thanks for your interest in this project.
I do not reproduce your issue, would you mind sharing your configuration yaml?

**Comment by Texier54** [comment]
I have the latest version of esphome

Yes :

esphome:
  name: stove
  friendly_name: Stove

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
    level: DEBUG  # INFO for less log, put DEBUG to view all the linky's received info in the logs

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.36
    gateway: 192.168.1.1       # L'adresse de la passerelle, généralement celle de votre routeur
    subnet: 255.255.255.0      # Masque de sous-réseau

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Stove Fallback Hotspot"
    password: ""

captive_portal:

external_components:
  - source:
        type: git
        url: https://github.com/n-serrette/esphome_rika_gsm
        ref: main
    components: [ rika_gsm ]

uart:
  id: rika_uart_bus
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 38400

rika_gsm:
  id: ria_gsm_component_1
  pin: "1234"
  phone_number: "+33685967412"

**Comment by n-serrette** [comment]
Thanks for your config, I was able to reproduce the issue, an include was missing in the .h.
Could you confirm it work for you by using the branch ```fix_2_compile_issue```?

**Comment by Texier54** [comment]
Yes it works, thanks for the fix !

**Comment by n-serrette** [comment]
the change are now merged into the main branch
